2016-05-13 22:40:18,149 : INFO : Machine : Mission Pinball Framework Core Engine v0.30.0.dev1482
2016-05-13 22:40:18,150 : INFO : Machine : Machine path: /Users/gabe/Dropbox/Pinball/Gabe/bnd
2016-05-13 22:40:18,371 : INFO : Machine : Loading cached config: /var/folders/c1/z5pg47y54_s14cd2m1zmk1kc0000gn/T/db0cb78b77a969ed262a283d7c7743faconfig
2016-05-13 22:40:18,372 : INFO : Machine : Starting clock at 30.0Hz
2016-05-13 22:40:18,388 : INFO : FAST : Configuring FAST hardware.
2016-05-13 22:40:18,388 : INFO : Machine : Loading core modules...
2016-05-13 22:40:18,398 : INFO : FAST : Configuring FAST Controller for FAST IO boards.
2016-05-13 22:40:18,398 : INFO : FAST : Connecting to /dev/tty.usbserial-141C at 921600bps
2016-05-13 22:40:19,917 : INFO : FAST : Received ID acknowledgement. Processor: RGB, Board: FP-CPU-002-2, Firmware: 01.00
2016-05-13 22:40:19,918 : INFO : FAST : Connecting to /dev/tty.usbserial-141B at 921600bps
2016-05-13 22:40:21,435 : INFO : FAST : Received ID acknowledgement. Processor: NET, Board: FP-CPU-002-2, Firmware: 01.00
2016-05-13 22:40:21,452 : INFO : FAST : Fast IO Board 00: Model: FP-I/O-3208-2, Firmware: 01.00, Switches: 32, Drivers: 8
2016-05-13 22:40:21,467 : INFO : FAST : Fast IO Board 01: Model: FP-I/O-3208-2, Firmware: 01.00, Switches: 32, Drivers: 8
2016-05-13 22:40:21,468 : INFO : FAST : Fast IO Board 02: Model: FP-I/O-1616-2, Firmware: 01.00, Switches: 16, Drivers: 16
2016-05-13 22:40:21,501 : ERROR : root : 'pololu_maestro'
Traceback (most recent call last):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 120, in __init__
    self._initialize_platforms()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 178, in _initialize_platforms
    platform.initialize()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/platforms/pololu_maestro.py", line 39, in initialize
    None)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 789, in get_platform_sections
    if self.config['hardware'][platform_section] != 'default':
KeyError: 'pololu_maestro'
